name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: |
            -args: [--frozen-lockfile. --strict-peer-dependencies]
      - uses: actions/setup-node@v3
        with:
          node-version: '>=16.14.2'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run docs:build

      # 部署到 GitHub Pages
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
